<?php
namespace App\Mod\ContentModel\Domain;

use App\Domain\BaseService;
use Symfony\Component\HttpFoundation\Request;
use App\Mod\ContentModel\Domain\Models\ContentModel;
use Illuminate\Validation\Rule;

/**
 * @property ContentModel $model
 */
class ContentModelService extends BaseService
{

    public function __construct(ContentModel $model)
    {
        parent::__construct($model);
    }

    public function findList(Request $request, ?int $limit = null, array $with = []): array
    {
        if (!$limit) {
            $limit = config('content_model.list.limit');
        }
        return parent::findList($request, $limit, $with); // TODO: Change the autogenerated stub
    }

    protected function validateRequest(Request $request, mixed $post = null): void
    {
        $request->validate(
            [
                "title" => ['required'],
                'alias' => ['required', Rule::unique($this->model->getTable(), 'alias')->ignore($post->id)]
            ],
            [
                'title.required' => 'タイトルは必須項目です。',
                'alias.required' => 'エイリアスは必須項目です。',
                'alias.unique' => 'このエイリアスは既に使用されています。'
            ]
        );
    }
}
