<?php
namespace App\Mod\ActionLog\Domain;

use App\Domain\BaseService;
use Symfony\Component\HttpFoundation\Request;
use App\Mod\ActionLog\Domain\Models\ActionLog;

class ActionLogService extends BaseService
{

    public function __construct(ActionLog $model)
    {
        parent::__construct($model);
    }

    public function findList(Request $request, ?int $limit = null): array
    {
        if (!$limit) {
            $limit = config('action_log.list.limit');
        }
        return parent::findList($request, $limit); // TODO: Change the autogenerated stub
    }

}
