<?php
namespace App\Mod\Content\Domain;

use Symfony\Component\HttpFoundation\Request;
use App\Mod\Content\Domain\Models\ContentCategory;
use App\Mod\ContentModel\Domain\Models\ContentModel;

/**
 * @property ContentCategory $model
 * @property ContentModel $contentModel 
 */
class ContentCategoryService extends AbstractService
{
    public function __construct(ContentCategory $model)
    {
        parent::__construct($model);
    }

    public function findList(Request $request, ?int $limit = null, array $with = []): array
    {
        if (!$limit) {
            $limit = config('content.list.limit');
        }
        return parent::findList($request, $limit, $with); // TODO: Change the autogenerated stub
    }

    protected function validateRequest(Request $request, mixed $post = null): void
    {
        $request->validate(
            [
                'title' => ['required']
            ],
            [
                'title.required' => 'タイトルは必須項目です。'
            ]
        );
    }
}
