<?php
namespace App\Mod\Content\Domain;

use App\Domain\BaseService;
use Symfony\Component\HttpFoundation\Request;
use App\Mod\Content\Domain\Models\Content;
use App\Mod\ContentModel\Domain\Models\ContentModel;
use Illuminate\Support\Facades\Route;

/**
 * @property Content $model
 * @property ContentModel $contentModel 
 */
class ContentService extends BaseService
{
    protected $contentModel;

    public function __construct(Content $model)
    {
        parent::__construct($model);
        
        // Content Modelの取得
        $route = Route::current();
        $modelName = $route->parameter('model_name');
        if (!$modelName) {
            abort(404);
        }
        $contentModel = ContentModel::where('alias', $modelName)->first();
        if (!$contentModel) {
            abort(404);
        }
        $this->contentModel = $contentModel;
    }

    public function findList(Request $request, ?int $limit = null, array $with = []): array
    {
        if (!$limit) {
            $limit = config('content.list.limit');
        }
        return parent::findList($request, $limit, $with); // TODO: Change the autogenerated stub
    }

    protected function appendCriteria($criteria = [], $query): void
    {
        // デフォルトでmodelでフィルター
        $query->where('model_id', $this->contentModel->id);

        parent::appendCriteria($criteria, $query);
    }

}
